let inputWitdh;
let inputHeight;
inputWitdh = prompt("Enter the width:");
inputHeight = prompt("Enter the Heigth:");
let width = parseInt(inputWitdh);
let height =  parseInt(inputHeight);
let area = width * height;
document.write('Enter width: ');
document.write('<br>' );
document.write( + width);
document.write('<br>' );
document.write('Enter height: ');
document.write('<br>' );
document.write( + height);
document.write('<br>' );
document.write('The area is: ');
document.write('<br>' );
document.write(+ area);